### ISSUE TITLE
Serious error in gettin %includes

### ISSUE THREAD

**Issue by tpgxyz** [OpenMandrivaAssociation/omdv-build-iso#10]
@itchka @cris-b 
This is serious regression.
Looks like getIncFiles() or createPkgList() does not follow %include in lst files. That's why iso build for 3.0 fails with error:
dracut: dracut module 'mdraid' cannot be found or installed.
See here: https://abf.openmandriva.org/platforms/3.0/products/38/product_build_lists/284

Dracut fails because mdadm package is not installed. This package is in omdv_iso_minimal.lst.

Here is the chain.
omdv-plasma.lst:%include .///omdv_iso.lst
omdv_iso.lst:%include .///omdv_iso_minimal.lst

I have feeling that we went way too far than the point where script was useable and not bloated :(

**Comment by itchka** [comment]
Hi Tomek
First I will check the lists and if it is there I know how to fix it.
it's an oversightand and simple to fix.  Next time I do anything I'll have to 
do more testing in ABF=1 mode. I'll sort it
Colin

**Comment by tpgxyz** [comment]
I've checked lst files and these looks fine. Something is wrong inside bash functions.

**Comment by itchka** [comment]
Tomek,
Your are right but I hanve't solved it so I have re-instaled your package list 
function for the omspin until I have fixed it.
Will post the fix after I have built iso locally. Debugging  now shows the 
file mdadm is now installed so this is juyst a final check.
Colin

**Comment by tpgxyz** [comment]
Ok waiting for a real fix from you.

**Comment by itchka** [comment]
Tomek,
Temporary change pushed to master
I have found part of the problem (aghh the dangers of cut and paste) but use 
this simple fix for the time being.
Colin

**Comment by itchka** [comment]
Use global variable instead of local. Now fixed
