### ISSUE TITLE
ISO for 3.0 does not build

### ISSUE THREAD

**Issue by tpgxyz** [OpenMandrivaAssociation/omdv-build-iso#7]
@itchka can you please fix it ?

https://abf.openmandriva.org/platforms/3.0/products/38/product_build_lists/261
omspin
Creating OpenMandriva spin
cat: /tmp/isobuildrootOhGVoQ/iso-pkg-lists-3.0/omdv-plasma.lst: No such file or directory
cat: /tmp/isobuildrootOhGVoQ/iso-pkg-lists-3.0/omdv-plasma.lst: No such file or directory
Updating chroot
No rpms need to be installed

**Comment by itchka** [comment]
Will try but I think there's a an issue with abf I'll check and report back.
Colin

**Comment by tpgxyz** [comment]
Seems fixed.
